#!/bin/sh
echo "    Welcome to the eAdventure platform (v1.5 RC4)"
echo
echo "    You can find more information about the project at:"
echo "        http://e-adventure.e-ucm.es"
echo
echo "    We hope you will find the game editor useful. Please do not hesitate"
echo "    to contact us with suggestions and bug reports via e-mail: e-adventure@e-ucm.es"
echo "        e-adventure@e-ucm.es"
echo
echo "    (C)2005-2012 e-UCM research group"

JAVA_OPTS="$JAVA_OPTS -Xms256m -Xmx512m"
EDITOR_HOME="$HOME/.eadventure"
EADVENTURE_HOME="/usr/share/java/e-adventure/eadventure"
CFG_EDITOR="config_editor.xml"
JAR_NAME="eadventure-editor.jar"

# If first use, create local editor working directory; bail if failure
if ! [ -d "$EDITOR_HOME" ]; then
  echo "$EDITOR_HOME not found - creating local installation"
  if ! (\
        mkdir "$EDITOR_HOME" && \
        ln -s "$EADVENTURE_HOME"/* "$EDITOR_HOME" && \
        rm "$EDITOR_HOME/$CFG_EDITOR" "$EDITOR_HOME/web" && \
        cp -r "$EADVENTURE_HOME/$CFG_EDITOR" "$EADVENTURE_HOME/web" \
           "$EDITOR_HOME") ; 
    then
    
    echo "Error creating local installation; sorry :-("
    #rm -rf $EDITOR_HOME
  else
    echo "Created local installation. You are ready to edit!".
  fi
fi  

# Look for the right JVM to use

if ! [ -x "$JAVACMD" ]; then
  JAVACMD=$(which java)
fi
if ! [ -x "$JAVACMD" ]; then
  JAVACMD="$JAVA_HOME/bin/java"
fi

if [ -x "$JAVACMD" ] ; then
  OLDPWD=$(pwd)
  cd "$EDITOR_HOME"
  $JAVACMD $JAVA_OPTS -jar $JAR_NAME $@
  cd $OLDPWD
else
  echo "No JVM found to run e-Adventure"
  echo "Please install a JVM (>= 1.6) to run e-Adventure or "
  echo "set JAVA_HOME if it is not a JVM from a Debian Package."
  exit 1
fi
